src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Enum\EtatEnum;
use App\Repository\BlogRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\Persistence\Event\LifecycleEventArgs as EventLifecycleEventArgs;

#[ORM\Entity(repositoryClass: BlogRepository::class)]
class Blog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Contenu = null;

    #[ORM\Column(length: 255)]
    private ?string $Titre = null;

    #[ORM\Column(type: 'integer', options: ['default' => 0])]
    private int $rate = 0;
    
    #[ORM\Column(type: 'integer', options: ['default' => 0])]
    private int $rateCount = 0; // Count of ratings
    

    

    /**
     * @var Collection<int, Commentaire>
     */
    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'blog')]
    private Collection $listeCommentaires;

    #[ORM\Column(length: 255, enumType: EtatEnum::class, options: ["default" => "enAttente"])]
    private EtatEnum $statut = EtatEnum::enAttente;

    #[ORM\ManyToOne(inversedBy: 'blogs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;
    

    public function __construct()
    {
        $this->listeCommentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): static
    {
        $this->Contenu = $Contenu;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): static
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getRateCount(): int
    {
        return $this->rateCount;
    }
    public function getRate(): float
    {
        return $this->rateCount > 0 ? $this->rate / $this->rateCount : 0;
    }
    
    public function addRate(int $rating): self
    {
        if ($rating >= 0 && $rating <= 5) {
            $this->rate += $rating;
            $this->rateCount++;
        }
        return $this;
    }
    public function setRate(int $rate): static
    {
        $this->rate = $rate;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getListeCommentaires(): Collection
    {
        return $this->listeCommentaires;
    }

    public function addListeCommentaire(Commentaire $listeCommentaire): static
    {
        if (!$this->listeCommentaires->contains($listeCommentaire)) {
            $this->listeCommentaires->add($listeCommentaire);
            $listeCommentaire->setBlog($this);
        }

        return $this;
    }

    public function removeListeCommentaire(Commentaire $listeCommentaire): static
    {
        if ($this->listeCommentaires->removeElement($listeCommentaire)) {
            // set the owning side to null (unless already changed)
            if ($listeCommentaire->getBlog() === $this) {
                $listeCommentaire->setBlog(null);
            }
        }

        return $this;
    }

    public function getStatut(): EtatEnum
    {
        return $this->statut;
    }

    public function setStatut(EtatEnum $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }



public function getImage(): ?string
{
    return $this->image;
}

public function setImage(?string $image): static
{
    $this->image = $image;

    return $this;
}

}

src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $ContenuCmt = null;

    #[ORM\ManyToOne(inversedBy: 'listeCommentaires')]
    private ?Blog $blog = null;


    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user ;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenuCmt(): ?string
    {
        return $this->ContenuCmt;
    }

    public function setContenuCmt(string $ContenuCmt): static
    {
        $this->ContenuCmt = $ContenuCmt;

        return $this;
    }

    public function getBlog(): ?Blog
    {
        return $this->blog;
    }

    public function setBlog(?Blog $blog): static
    {
        $this->blog = $blog;

        return $this;
    }



    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }


}

src/Form/BlogType.php
<?php

namespace App\Form;

use App\Entity\Blog;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BlogType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('Titre')
        ->add('Contenu')
        ->add('imageFile', FileType::class, [
            'label' => 'Blog Image',
            'required' => false,
            'mapped' => false, // This field is not mapped to the entity
        ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Blog::class,
        ]);
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Enum\EtatEnum;
use App\Entity\Blog;
use App\Form\BlogType;
use App\Repository\BlogRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/blog')]
final class BlogController extends AbstractController
{
    #[Route('/blogs', name: 'app_blog_index', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $acceptedBlogs = $entityManager->getRepository(Blog::class)->findBy(
            ['statut' => EtatEnum::Acceptée],
            ['id' => 'DESC'] // Order by id in descending order
        );
        
    
        return $this->render('blog/index.html.twig', [
            'blogs' => $acceptedBlogs,
        ]);
    }
    #[Route('/all', name: 'app_blog_all', methods: ['GET'])]
    public function display(EntityManagerInterface $entityManager): Response
    {
        // Fetch the blogs sorted by their status (accepted, pending, rejected)
        $acceptedBlogs = $entityManager->getRepository(Blog::class)->findBy(
            ['statut' => 'Acceptée'], // Filter for accepted blogs
            ['id' => 'DESC'] // You can change this to the field you want to sort by
        );
        
        $pendingBlogs = $entityManager->getRepository(Blog::class)->findBy(
            ['statut' => 'enAttente'], // Filter for pending blogs
            ['id' => 'DESC']
        );
        
        $rejectedBlogs = $entityManager->getRepository(Blog::class)->findBy(
            ['statut' => 'Rejetée'], // Filter for rejected blogs
            ['id' => 'DESC']
        );
    
        // Combine the blogs into one array, maintaining the order: Accepted, Pending, Rejected
        $allBlogs = array_merge($acceptedBlogs, $pendingBlogs, $rejectedBlogs);
    
        return $this->render('blog/all_blogs.html.twig', [
            'blogs' => $allBlogs,
        ]);
    }
    
    
    #[Route('/new', name: 'app_blog_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        
        $blog = new Blog();
        $blog->setUser($this->getUser());
        
        // If the logged-in user is an admin, set the blog's status to accepted right away
        if (in_array('ROLE_ADMIN', $this->getUser()->getRoles())) {
            $blog->setStatut(EtatEnum::Acceptée); // Automatically set the status to "accepted"
        }
        
        $form = $this->createForm(BlogType::class, $blog);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imageFile */
            $imageFile = $form->get('imageFile')->getData();
        
            if ($imageFile) {
                $newFilename = uniqid().'.'.$imageFile->guessExtension();
        
                // Move the file to the directory where images are stored
                $imageFile->move(
                    $this->getParameter('images_directory'),
                    $newFilename
                );
        
                // Update the 'image' property to store the file name
                $blog->setImage($newFilename);
            }
        
            $entityManager->persist($blog);
            $entityManager->flush();
        
            return $this->redirectToRoute('app_blog_index', [], Response::HTTP_SEE_OTHER);
        }
        
        return $this->render('blog/new.html.twig', [
            'blog' => $blog,
            'form' => $form,
        ]);
    }
    

    #[Route('/{id}', name: 'app_blog_show', methods: ['GET'])]
    public function show(Blog $blog): Response
    {
        return $this->render('blog/show.html.twig', [
            'blog' => $blog,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_blog_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Blog $blog, EntityManagerInterface $entityManager): Response
    {
        // Ensure the user is either the blog owner or an admin
        $this->denyAccessUnlessGranted('ROLE_USER');  // Basic check for regular users
    
        // If the user is an admin, automatically accept the blog
        if ($this->isGranted('ROLE_ADMIN')) {
            $blog->setStatut(EtatEnum::Acceptée);  // Admin automatically accepts the blog
        } else {
            // Ensure only the blog owner can access the edit page
            if ($blog->getUser() !== $this->getUser()) {
                throw $this->createAccessDeniedException('You are not allowed to edit this blog.');
            }
            
            // Set the blog status to 'enAttente' when it is edited by a regular user
            $blog->setStatut(EtatEnum::enAttente);  // Set status to "pending" for approval by admin
        }
    
        $form = $this->createForm(BlogType::class, $blog);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
        
            // Redirect to the index page or any other page you wish after updating
            $this->addFlash('success', 'Blog updated successfully!');
            return $this->redirectToRoute('app_blog_index');
        }
        
        return $this->render('blog/edit.html.twig', [
            'blog' => $blog,
            'form' => $form,
        ]);
    }
    


    #[Route('/{id}', name: 'app_blog_delete', methods: ['POST'])]
    public function delete(Request $request, Blog $blog, EntityManagerInterface $entityManager): Response
    {
        // Ensure only the blog owner can delete the blog
        if ($blog->getUser() !== $this->getUser()) {
            throw $this->createAccessDeniedException('You are not allowed to delete this blog.');
        }
    
        if ($this->isCsrfTokenValid('delete' . $blog->getId(), $request->getPayload()->getString('_token'))) {
            // Remove related comments first
            foreach ($blog->getListeCommentaires() as $comment) {
                $entityManager->remove($comment);
            }
    
            // Remove the blog
            $entityManager->remove($blog);
            $entityManager->flush();
        }
    
        return $this->redirectToRoute('app_blog_index', [], Response::HTTP_SEE_OTHER);
    }
    
    #[Route('/admin/pending-blogs', name: 'admin_pending_blogs')]
    public function showPendingBlogs(BlogRepository $blogRepository)
    {
        // Find all blogs with the status "enAttente"
        $blogs = $blogRepository->findBy(['statut' => EtatEnum::enAttente]);

        return $this->render('admin/pending_blogs.html.twig', [
            'blogs' => $blogs,
        ]);
    }
    #[Route('/accept/{id}', name: 'accept_blog', methods: ['GET'])]

    public function acceptBlog(int $id, EntityManagerInterface $entityManager): RedirectResponse
    {
        // Find the blog by its ID
        $blog = $entityManager->getRepository(Blog::class)->find($id);
        
        if (!$blog) {
            // If the blog is not found, show an error message
            $this->addFlash('error', 'Blog not found!');
            return $this->redirectToRoute('app_blog_index');
        }
        
        // Check if the blog is already accepted
        if ($blog->getStatut() === EtatEnum::Acceptée) {
            $this->addFlash('info', 'This blog is already accepted.');
            return $this->redirectToRoute('app_blog_index'); // Redirect to index to show flash message
        }
        
        // Update the blog's statut to 'Acceptée'
        $blog->setStatut(EtatEnum::Acceptée);
        $entityManager->flush();
        
        // Add a success message to the flash bag
        $this->addFlash('success', 'Blog accepted successfully!');
        
        // Redirect back to the index page
        return $this->redirectToRoute('app_blog_index');
    }
    #[Route('/reject/{id}', name: 'reject_blog', methods: ['GET'])]
public function rejectBlog(int $id, EntityManagerInterface $entityManager): RedirectResponse
{
    // Find the blog by its ID
    $blog = $entityManager->getRepository(Blog::class)->find($id);
    
    if (!$blog) {
        // If the blog is not found, show an error message
        $this->addFlash('error', 'Blog not found!');
        return $this->redirectToRoute('app_blog_index');
    }
    
    // Check if the blog is already rejected
    if ($blog->getStatut() === EtatEnum::Rejetée) {
        $this->addFlash('info', 'This blog is already rejected.');
        return $this->redirectToRoute('app_blog_index'); // Redirect to index to show flash message
    }
    
    // Update the blog's statut to 'Rejetée'
    $blog->setStatut(EtatEnum::Rejetée);
    $entityManager->flush();
    
    // Add a success message to the flash bag
    $this->addFlash('success', 'Blog rejected successfully!');
    
    // Redirect back to the index page
    return $this->redirectToRoute('app_blog_index');
}

#[Route('/rate/{id}', name: 'app_blog_rate', methods: ['POST'])]
public function rateBlog(Request $request, Blog $blog, EntityManagerInterface $entityManager): Response
{
    
    $rating = (int) $request->request->get('rating');
    $this->denyAccessUnlessGranted('ROLE_USER');  // Basic check for regular users

    if ($rating < 0 || $rating > 5) {
        $this->addFlash('error', 'Invalid rating. Please select a value between 0 and 5.');
        return $this->redirectToRoute('app_blog_index');
    }

    $blog->addRate($rating);
    $entityManager->flush();

    $this->addFlash('success', 'Rating added successfully!');

templates/blog/_delete_form.html.twig
<form method="post" action="{{ path('app_blog_delete', {'id': blog.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ blog.id) }}">
    <button class="btn">Delete</button>
</form>

templates/blog/_form.html.twig
{{ form_start(form, {'attr': {'enctype': 'multipart/form-data'}}) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/blog/all_blogs.html.twig
{% extends 'layout/header.html.twig' %}

{% block title %}Blog List{% endblock %}

{% block body %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

<style>
    /* Custom Styles */
    body {
        background: linear-gradient(135deg, #f5f7fa, #c3cfe2);
        font-family: 'Poppins', sans-serif;
    }

    .card {
        border: none;
        border-radius: 20px;
        background: rgba(255, 255, 255, 0.9);
        backdrop-filter: blur(15px);
        box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
        transition: transform 0.3s ease, box-shadow 0.3s ease;
        overflow: hidden;
        position: relative; /* Required for FAB positioning */
    }

    .card:hover {
        transform: translateY(-10px);
        box-shadow: 0 12px 40px rgba(0, 0, 0, 0.2);
    }

    .card img {
        border-top-left-radius: 20px;
        border-top-right-radius: 20px;
        height: 250px;
        object-fit: cover;
        transition: transform 0.3s ease;
    }

    .card:hover img {
        transform: scale(1.05);
    }

    .card-title {
        font-size: 1.5rem;
        font-weight: 700;
        color: #2c3e50;
        margin-bottom: 10px;
    }

    .card-text {
        font-size: 1rem;
        color: #555;
        line-height: 1.6;
    }

    .badge {
        font-size: 0.9rem;
        text-transform: capitalize;
        padding: 8px 12px;
        border-radius: 20px;
        background: linear-gradient(135deg, #6c757d, #495057);
        color: white;
    }

    .btn-primary, .btn-success, .btn-warning, .btn-danger {
        border-radius: 25px;
        padding: 10px 20px;
        font-size: 0.9rem;
        font-weight: 500;
        transition: all 0.3s ease;
        border: none;
    }

    .btn-primary {
        background: linear-gradient(135deg, #007bff, #0056b3);
    }

    .btn-primary:hover {
        background: linear-gradient(135deg, #0056b3, #003d80);
    }

    .btn-success {
        background: linear-gradient(135deg, #28a745, #218838);
    }

    .btn-success:hover {
        background: linear-gradient(135deg, #218838, #1e7e34);
    }

    .btn-warning {
        background: linear-gradient(135deg, #ffc107, #e0a800);
    }

    .btn-warning:hover {
        background: linear-gradient(135deg, #e0a800, #d39e00);
    }

    .btn-danger {
        background: linear-gradient(135deg, #dc3545, #c82333);
    }

    .btn-danger:hover {
        background: linear-gradient(135deg, #c82333, #bd2130);
    }

    .comment-section {
        background: rgba(248, 249, 250, 0.9);
        backdrop-filter: blur(15px);
        border-radius: 25px;
        padding: 20px;
        margin-top: 20px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
    }

    .comment-section h6 {
        font-size: 1.2rem;
        font-weight: 600;
        color: #6c757d;
    }

    .list-group-item {
        border: none;
        padding: 15px;
        background: rgba(255, 255, 255, 0.9);
        margin-bottom: 10px;
        border-radius: 15px;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
        transition: all 0.3s ease;
    }

    .list-group-item:hover {
        transform: translateX(10px);
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
    }

    .rating {
        display: flex;
        align-items: center;
    }

    .rating i {
        margin-right: 5px;
        color: #ffc107;
        cursor: pointer;
        transition: all 0.2s ease;
        font-size: 1.5rem;
    }

    .rating i:hover,
    .rating i.active {
        color: #ffc107;
        transform: scale(1.2);
    }

    .rating i.active {
        color: #ffc107;
    }

    .flash-message {
        border-radius: 15px;
        margin-bottom: 20px;
        padding: 15px;
        text-align: center;
        font-weight: 500;
        background: rgba(255, 255, 255, 0.9);
        backdrop-filter: blur(15px);
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
    }

    .container {
        max-width: 1200px;
        margin: 0 auto;
    }

    h1.text-center {
        font-size: 2.5rem;
        font-weight: 700;
        color: #2c3e50;
        margin-bottom: 30px;
        text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1);
    }

    .text-muted {
        color: #6c757d !important;
    }

    /* Floating Action Button (FAB) */
    .fab {
        position: absolute;
        bottom: 20px;
        right: 20px;
        background: linear-gradient(135deg, #007bff, #0056b3);
        color: white;
        border: none;
        border-radius: 50%;
        width: 40px;
        height: 40px;
        font-size: 1.5rem;
        display: flex;
        align-items: center;
        justify-content: center;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
        transition: all 0.3s ease;
        cursor: pointer;
    }

    .fab:hover {
        transform: scale(1.1);
        box-shadow: 0 6px 16px rgba(0, 0, 0, 0.3);
    }
</style>
<div class="container mt-5">
    <h1 class="text-center mb-4">Blog List</h1>

    {# Flash messages #}
    {% for label, messages in app.flashes %}
        <div class="alert alert-{{ label }} text-center">
            {% for message in messages %}
                <p class="mb-0">{{ message }}</p>
            {% endfor %}
        </div>
    {% endfor %}

    {# Grouping Blogs by Status #}
    <div class="row">

        {# Display Accepted Blogs #}
        <div class="col-12 mb-4">
            <h3 class="text-success">Accepted Blogs</h3>
            {% set acceptedBlogs = blogs|filter(blog => blog.statut.value == 'Acceptée') %}
            <div class="row">
                {% for blog in acceptedBlogs %}
                    <div class="col-md-4 mb-4">
                        <div class="card shadow-lg">
                            {% if blog.image %}
                            <img src="{{ asset('uploads/images/' ~ blog.image) }}" alt="{{ blog.Titre }}" class="img-fluid">
                            {% else %}
                            <img src="{{ asset('uploads/images/blog.jpg') }}" alt="{{ blog.Titre }}" class="img-fluid">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title text-primary">{{ blog.titre }}</h5>
                                <p class="card-text text-muted">{{ blog.contenu|slice(0, 100) ~ '...' }}</p>
                                <p class="mb-2">
                                    <strong>Posted by:</strong> {{ blog.user.username }}
                                </p>
                                <p class="mb-2">
                                    <strong>Status:</strong>
                                    <span class="badge btn-success">
                                        {{ blog.statut.value }}
                                    </span>
                                </p>
                                <a href="{{ path('app_blog_show', {'id': blog.id}) }}" class="btn btn-primary btn-sm">Read More</a>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <p class="text-muted">No accepted blogs found.</p>
                {% endfor %}
            </div>
        </div>

        {# Display Pending Blogs #}
        <div class="col-12 mb-4">
            <h3 class="text-warning">Pending Blogs</h3>
            {% set pendingBlogs = blogs|filter(blog => blog.statut.value == 'enAttente') %}
            <div class="row">
                {% for blog in pendingBlogs %}
                    <div class="col-md-4 mb-4">
                        <div class="card shadow-lg">
                            {% if blog.image %}
                            <img src="{{ asset('uploads/images/' ~ blog.image) }}" alt="{{ blog.Titre }}" class="img-fluid">
                            {% else %}
                            <img src="{{ asset('uploads/images/blog.jpg') }}" alt="{{ blog.Titre }}" class="img-fluid">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title text-primary">{{ blog.titre }}</h5>
                                <p class="card-text text-muted">{{ blog.contenu|slice(0, 100) ~ '...' }}</p>
                                <p class="mb-2">
                                    <strong>Posted by:</strong> {{ blog.user.username }}
                                </p>
                                <p class="mb-2">
                                    <strong>Status:</strong>
                                    <span class="badge btn-warning">
                                        {{ blog.statut.value }}
                                    </span>
                                </p>
                                <a href="{{ path('app_blog_show', {'id': blog.id}) }}" class="btn btn-primary btn-sm">Read More</a>
                                <a href="{{ path('accept_blog', {'id': blog.id}) }}" class="btn btn-success btn-sm">Accept</a>
                                <a href="{{ path('reject_blog', {'id': blog.id}) }}" class="btn btn-danger btn-sm">Reject</a>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <p class="text-muted">No pending blogs found.</p>
                {% endfor %}
            </div>
        </div>

        {# Display Rejected Blogs #}
        <div class="col-12 mb-4">
            <h3 class="text-danger">Rejected Blogs</h3>
            {% set rejectedBlogs = blogs|filter(blog => blog.statut.value == 'Rejetée') %}
            <div class="row">
                {% for blog in rejectedBlogs %}
                    <div class="col-md-4 mb-4">
                        <div class="card shadow-lg">
                            {% if blog.image %}
                            <img src="{{ asset('uploads/images/' ~ blog.image) }}" alt="{{ blog.Titre }}" class="img-fluid">
                            {% else %}
                            <img src="{{ asset('uploads/images/blog.jpg') }}" alt="{{ blog.Titre }}" class="img-fluid">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title text-primary">{{ blog.titre }}</h5>
                                <p class="card-text text-muted">{{ blog.contenu|slice(0, 100) ~ '...' }}</p>
                                <p class="mb-2">
                                    <strong>Posted by:</strong> {{ blog.user.username }}
                                </p>
                                <p class="mb-2">
                                    <strong>Status:</strong>
                                    <span class="badge btn-danger">
                                        {{ blog.statut.value }}
                                    </span>
                                </p>
                                <a href="{{ path('app_blog_show', {'id': blog.id}) }}" class="btn btn-primary btn-sm">Read More</a>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <p class="text-muted">No rejected blogs found.</p>
                {% endfor %}
            </div>
        </div>

    </div>

</div>
{% endblock %}

templates/blog/approve.html.twig
{% extends 'layout/header.html.twig' %}

{% block title %}Approve Blogs{% endblock %}

{% block body %}
    <h1>Pending Blogs</h1>

    {% if blogs is empty %}
        <p>No pending blogs.</p>
    {% else %}
        <table border="1">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Content</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for blog in blogs %}
                    <tr>
                        <td>{{ blog.id }}</td>
                        <td>{{ blog.title }}</td>
                        <td>{{ blog.content|slice(0, 100) ~ '...' }}</td>
                        <td>
                            <a href="{{ path('accept_blog', {id: blog.id}) }}" class="btn btn-success">Accept</a>
                            <a href="{{ path('reject_blog', {id: blog.id}) }}" class="btn btn-danger">Reject</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

templates/blog/edit.html.twig
{% extends 'layout/header.html.twig' %}

{% block title %}Edit Blog{% endblock %}

{% block body %}
    <h1>Edit Blog</h1>

    {{ include('blog/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_blog_index') }}">back to list</a>

    {{ include('blog/_delete_form.html.twig') }}
{% endblock %}